services:
  app:
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=${MONGO_URL}
    networks:
      - appNetwork
  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo_data:/data/db
    networks:
      - appNetwork

networks:
  appNetwork:
    driver: bridge

volumes:
  mongo_data:
